[build]
  publish = "NON21SEPT_SITE_FULL_v18_MOD"
  command = ""

[[redirects]]
  from = "/petition"
  to   = "/petition/index.html"
  status = 200
  force  = true

[[redirects]]
  from = "/petition/*"
  to   = "/petition/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
